### ISSUE TITLE
не zapuskaetsa

### ISSUE THREAD

**Issue by tischenkob** [rukavishnikovmihail00/YouTube-downloader#1]
Окошко появляется на один кадр и исчезает

**Comment by tischenkob** [comment]
После pip install pytube : 
ImportError: cannot import name 'quote' from 'pytube.compat'

**Comment by rukavishnikovmihail00** [comment]
Try to uninstall pytube and run ‘pip install pytube3’

**Comment by tischenkob** [comment]
That solved the issue, thanks!
